name: Upload Habachen

on:
  push:
    tags:
      - '*'

jobs:
  update_and_build_sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Extract Version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "version=$VERSION" >> $GITHUB_ENV
      - name: Update Version
        run: |
          sed -i "s/version = '.*'/version = '${{ env.version }}'/" setup.py
          sed -i "s/__version__ = '.*'/__version__ = '${{ env.version }}'/" ./habachen/_version.py
          git config --global user.name "${{ secrets.MY_USERNAME }}"
          git config --global user.email "${{ secrets.MY_EMAIL }}"
          git add .
          if git diff --staged --quiet; then
            echo "No version changes have been made"
          else
            git commit -m "updated to ${{ github.ref_name }}"
            git push origin HEAD:main
          fi
      - name: Build sdist
        run: |
          pipx run build --sdist
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*.tar.gz

  build_wheels:
    needs: update_and_build_sdist
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Build wheels on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Turnout
        run: |
          git rm -f pyproject.toml
      - name: Build
        uses: pypa/cibuildwheel@v3.2.0
        env:
          CIBW_BUILD: cp38-* cp39-* cp310-* cp311-* cp312-* cp313-* cp314-* cp314t-*
          CIBW_ARCHS_LINUX: auto
          CIBW_ARCHS_MACOS: x86_64 universal2 arm64
          CIBW_PRERELEASE_PYTHONS: true
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  build_wheels_extra:
    needs: update_and_build_sdist
    runs-on: ubuntu-latest
    name: Build wheels for Linux arm64
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Turnout
        run: |
          git rm -f pyproject.toml
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: Build
        uses: pypa/cibuildwheel@v3.2.0
        env:
          CIBW_BUILD: cp38-* cp39-* cp310-* cp311-* cp312-* cp313-* cp314-* cp314t-*
          CIBW_ARCHS_LINUX: aarch64
          CIBW_PRERELEASE_PYTHONS: true
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-extra
          path: ./wheelhouse/*.whl

  build_wheels_cp313t:
    needs: update_and_build_sdist
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Build 3.13t wheels on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Turnout
        run: |
          git rm -f pyproject.toml
      - name: Build
        uses: pypa/cibuildwheel@v3.2.0
        env:
          CIBW_BUILD: cp313t-*
          CIBW_ARCHS_LINUX: auto
          CIBW_ARCHS_MACOS: x86_64 universal2 arm64
          CIBW_ENABLE: cpython-freethreading
          
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-cp313t
          path: ./wheelhouse/*.whl

  build_wheels_extra_cp313t:
    needs: update_and_build_sdist
    runs-on: ubuntu-latest
    name: Build 3.13t wheels for Linux arm64
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Turnout
        run: |
          git rm -f pyproject.toml
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: Build
        uses: pypa/cibuildwheel@v3.2.0
        env:
          CIBW_BUILD: cp313t-*
          CIBW_ARCHS_LINUX: aarch64
          CIBW_ENABLE: cpython-freethreading
      - uses: actions/upload-artifact@v4
        with:
          name: wheel-extra-cp313t
          path: ./wheelhouse/*.whl

  upload_pypi:
      needs: [update_and_build_sdist, build_wheels, build_wheels_extra]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/download-artifact@v4
          with:
            pattern: "*"
            path: dist
            merge-multiple: true
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install twine
            pip install -U packaging
        - name: Upload package
          run: |
            twine upload --repository pypi -u ${{ secrets.TOK_USERNAME }} -p ${{ secrets.TOK_PASSWORD }} dist/*
