name: Upload Habachen

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Update Version
        run: |
          python version_stmt.py ${{ github.ref_name }} > ./habachen/_version.py
          git config --global user.name "${{ secrets.MY_USERNAME }}"
          git config --global user.email "${{ secrets.MY_EMAIL }}"
          git add .
          git commit -m "updated to ${{ github.ref_name }}"
          git push origin HEAD:main
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine
      - name: Build package
        run: |
          python setup.py sdist
      - name: Upload package
        run: |
          twine upload --repository pypi -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }} dist/*
